# Default values for clusterbackup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "icr.io/cpopen/cp4waiops/cp4aiops-bcdr@sha256:d48e11fc4ec2fd841620c5d0d4bce45cf293d6464632838881c4c698a2a92ac2"
  pullPolicy: Always
schedule: ""
backupStorageLocation: ""
rwxStorageClass: ""
backupNameSuffix: ""
aiopsNamespace: ""
csNamespace: ""
oadpNamespace: ""
redisBackupPod: ""
redisPVC: ""
redisSecret: ""
esBackupPVC: "aiops-opensearch-snapshot-repo"
ttl: 72h0m0s
enabledNamespaces:
  - '"ibm-common-services"'
  - '"cp4aiops"'
enabledComponents:
  - '"AIOPS"'
  - '"IA"'
